# Generated by Django 2.2.13 on 2020-11-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currentStock',
            fields=[
                ('stock_code', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField()),
                ('average_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('earning_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='currentStockPrice',
            fields=[
                ('stock_code', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=30)),
                ('current_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='newsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news_data', models.CharField(max_length=300)),
                ('stock_name', models.CharField(max_length=30)),
                ('current_price', models.IntegerField()),
                ('rate_005930', models.IntegerField()),
                ('rate_000660', models.IntegerField()),
                ('rate_068270', models.IntegerField()),
                ('rate_096530', models.IntegerField()),
                ('rate_105560', models.IntegerField()),
                ('rate_055550', models.IntegerField()),
                ('rate_009540', models.IntegerField()),
                ('rate_133750', models.IntegerField()),
                ('rate_057030', models.IntegerField()),
                ('rate_035720', models.IntegerField()),
                ('rate_035420', models.IntegerField()),
                ('rate_035760', models.IntegerField()),
                ('rate_352820', models.IntegerField()),
                ('rate_009830', models.IntegerField()),
                ('rate_011780', models.IntegerField()),
                ('rate_011070', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stockReference',
            fields=[
                ('stock_code', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tradingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userRank',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('earning_rate', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
