# Generated by Django 2.2.13 on 2020-11-13 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='id',
            #field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            field=models.AutoField(null=True, blank=True, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrank',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
