# Generated by Django 2.2.13 on 2020-11-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201113_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
