# Generated by Django 2.2.13 on 2020-11-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201113_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
