# Generated by Django 2.2.13 on 2020-11-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201113_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrank',
            name='date',
        ),
    ]
