# Generated by Django 2.2.13 on 2020-11-13 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_userrank_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinglog',
            name='buy_count',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradinglog',
            name='sell_count',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradinglog',
            name='stock_code',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrank',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
