# Generated by Django 2.2.13 on 2020-11-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20201116_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstock',
            name='stock_code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currentstockprice',
            name='stock_code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockreference',
            name='stock_code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tradinglog',
            name='stock_code',
            field=models.CharField(max_length=30),
        ),
    ]
