# Generated by Django 2.2.13 on 2020-11-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201116_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
