# Generated by Django 2.2.13 on 2020-11-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_currentstock_previous_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='deposit',
            field=models.IntegerField(default=1000000),
        ),
    ]
