# Generated by Django 2.2.13 on 2020-11-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_userrank_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrank',
            name='id',
        ),
        migrations.AlterField(
            model_name='userrank',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
