# Generated by Django 2.2.13 on 2020-11-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20201117_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstock',
            name='stock_name',
            field=models.CharField(default='stock_name', max_length=30),
        ),
    ]
